FROM maven:latest AS maven-builder
WORKDIR /Reto-Accenture2024
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn test
RUN mvn package -DskipTests
FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=maven-builder /Reto-Accenture2024/target/accenture-techhub-0.0.1-SNAPSHOT.war app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]